version: '3'
# Create endpoint
# https://www.youtube.com/watch?v=w2_Dx8pd43w
services:
  postgres:
      image: postgres
      volumes:
        - ./keycloak/postgresql:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: ${POSTGRES_PASSWORD}
        KEYCLOAK_USER: ${KEYCLOAK_USER} 
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      volumes:
        - ./keycloak/keycloak_data:/opt/jboss/keycloak/standalone/data
      ports:
        - 8080:8080
      depends_on:
        - postgres
